creation_rules:
  - age: >-
      age1u7wl8lqsmpvnva2hj9fsl64z3ecmu6humlauhkuhjkdj6zgj4cyqy9xmcj,
      age1au8vyd694adhkhx0zcx7petanp0f8ajzglu7ysc50r94d5ear36sghlljl,
      age1407suy0ldzcfj4rjvxh3j88xtup0q89fwu0xgcrxyfvudksxevpskmd57r,
      age138wuhzcfyk3lluqt84k4kzm7tkuuxw5v89s3637qhng53366weeq4kz0u4,
      age1pz85hxkw9uhhqgul6jeej5pctutregpwgg8q477mgdvfdg0hxausnvcu5m